---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebdeployment
  labels:
    app: myweb
spec:
  replicas: 6
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels: null
      resources: null
  requests:
    cpu: "1"
    memory: 1Gi
    app: myweb
    spec:
      containers:
        - name: myweb
          image: amolgh1987/my011-5
          ports:
            - containerPort: 8080
